/** @type { import("@cspell/cspell-types").CSpellUserSettings } */
export default {
  ignorePaths: [
    "node_modules",
    "package.json",
    "pnpm-lock.yaml",
    "tsconfig.tsbuildinfo",
    "storybook-static",
    "coverage",
    "dist",
    ".sanity",
    "sanity.types.ts",
    "schema.json",
  ],
  words: [
    "cspell",
    "commitlint",
    "syncpack",
    "codeowners",
    "turborepo",
    "nextjs",
    "biomejs",
    "autodocs",
    "groq",
    "stega",
    "portabletext",
    "hotspot",
    "rgba",
    "lqip",
    "lefthook",
    "vueza",
  ],
};
